version: 3
project:
  locator: SolaceLabs_asyncapi-importer-core
  id: SolaceLabs_asyncapi-importer-core
  name: asyncapi-importer-core
  teams: []
  labels:
    - java
vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"
paths:
  exclude:
    - ./.git
    - ./.github
telemetry:
  scope: full
